### ISSUE TITLE
WebAssembly support or documentation

### ISSUE THREAD

**Issue by darioAnongba** [bitcoindevkit/bdk#1671]
BDK website states the following:
> Cross Platform
The core logic is feature rich allowing you to build any wallet from scratch on mobile, desktop and **even WebAssembly**.

Yet, when trying to use BDK in the browser or get some information about BDK and WebAssembly, I wasn't able to find anything on the documentation and looking into past issues, I was able to understand that some people were successful in compiling `bdk` to WASM. Yet these issues are years old for most and hard to navigate. I also found the [bdk-wasm](https://github.com/notmandatory/bdk-wasm) project from @notmandatory but this project is 2 years old and not up-to-date.

I understand that compiling to WASM is not similar to bindings and is more akin to targeting a specific environment but wouldn't a `bdk-wasm` repo be interesting as part of the `BDK` org? Or at least a tutorial section in the documentation?

I'll be happy to contribute to the project and create such repo if you deem it worth it, also writing the documentation for it.
- A simple tutorial explaining how to compile to WASM and create a package to use in browser/Node envs
- A `bdk-wasm` repo maintained and up-to-date with new BDK releases so that it can be tested for breaking changes and ensure that BDK is WASM compatible. Also serving as tutorial.

**Use case**  
Being able to use BDK in Node, browser or other JS environments.

**Additional context**
I'm personally trying to use BDK in a browser extension and having trouble obtaining a working package. My knowledge of Rust and WASM is limited and I still have much to learn.

**Comment by notmandatory** [comment]
Hi, thanks for opening an issue for this. I agree we do need a new updated WASM example. Have you taken a look at the https://github.com/MutinyWallet project to see how they used BDK 1.0 with WASM? If you can get a simple example it'd be a good addition to this repo. Or would be great to add WASM tutorial docs to the book of bdk documentation. https://github.com/bitcoindevkit/book-of-bdk

**Comment by darioAnongba** [comment]
Hi @notmandatory, I'll be happy to contribute and write a tutorial on the book-of-bdk.

WASM being a target, it needs to adapt to the env so, as you know better than me, we can only show examples. Nevertheless an "official" example also used to test if the BDK compiles successfully to WASM seems a good idea so a dedicated repo seems a good idea to me. 

In the meantime, for those looking to compile to WASM for browser, this is an example of what you need using `wasm-pack`:
```toml
[package]
name = "bdk-wasm"
...

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.95"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }
getrandom = { version = "0.2.15", features = ["js"] }
ring = { version = "0.17.8", features = ["wasm32_unknown_unknown_js"] }
bdk_wallet = { version = "1.0.0-beta.5" }
bdk_esplora = { version = "0.19.0", features = ["async-https"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.45"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
```

For MacOS M1/2/3 users, you will need to install `llvm` and point to it as the default C compiler cannot target WASM and fails for `secp256k1`:
```sh
brew install llvm
```
and
```toml
# In .cargo/config.toml for your project or globally in your `~/.zshrc`
[env]
AR = "/opt/homebrew/opt/llvm/bin/llvm-ar"
CC = "/opt/homebrew/opt/llvm/bin/clang"
```
