### ISSUE TITLE
Run BDK tests with github linux-arm runner

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/bdk#1889]
**Describe the enhancement**  

Currently BDK CI build-test job tests against the `ubuntu-latest` image. Github now offers a `ubuntu-24.04-arm` runner that we should also run the tests with. 

https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories

**Use case**  

BDK apps that are hosted in AWS might use their new Graviton servers that are based on ARM and should be tested with the `ubuntu-24.04-arm` Github runners.

**Additional context**

https://github.com/actions/partner-runner-images/blob/main/images/arm-ubuntu-24-image.md

**Comment by ItshMoh** [comment]
Hey @notmandatory  On looking the .github/workflows. I found that in this workflow https://github.com/bitcoindevkit/bdk/blob/master/.github/workflows/cont_integration.yml  build-test is being done. Now for adding the  
ubuntu-24.04-arm as a os. I have done something like this. 
```
build-test:
    needs: prepare
    name: Build & Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm64
```
I have also raised a PR(https://github.com/bitcoindevkit/bdk/pull/1905) for this issue. You can review it.
