### ISSUE TITLE
Consider not changing the version in `Cargo.toml` before the release is cut

### ISSUE THREAD

**Issue by thomaseizinger** [bitcoindevkit/bdk#496]
In order to depend on unreleased versions of libraries, `cargo` offers a way to patch a certain version of a dependency via the `[patch.crates-io]`.

This however only works if the version mentioned in the project `Cargo.toml` file is the same one as the one set in the dependency's manifest.

I am currently depending on bdk 0.14 and trying to patch `bdk` across my dependency graph to latest HEAD. Unfortunately, that doesn't work:

```
❯ cargo t
    Updating git repository `https://github.com/bitcoindevkit/bdk`
warning: Patch `bdk v0.14.1-dev (https://github.com/bitcoindevkit/bdk#64e88f0e)` was not used
in the crate graph.
Check that the patched package version and available features are compatible
with the dependency requirements. If the patch has a different version from
what is locked in the Cargo.lock file, run `cargo update` to use the new
version. This may also occur with an optional dependency that is not enabled.
```

Do people use the `[patch.crates-io]` feature? If yes, how are you dealing with pre-release version bumps in the manifest file?

**Comment by notmandatory** [comment]
If you just need to use the latest pre-released version then the patch method is a good way to go. But to use it you also need to specify the current version in the repo master branch, this will work:
```toml
[patch.crates-io]
bdk = { git = 'https://github.com/bitcoindevkit/bdk' }

[dependencies]
bdk = { version = "0.14.1-dev", default-features = false, features = ["all-keys"]}
```
